version: "3.8"
services:
  mongo:
    image: mongo:4.4.18-rc0-focal
    env_file:
      - ./mongo/.env
    restart: always
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
  backend:
    build: ./backend
    env_file:
      - ./backend/app/.env
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - mongo
volumes:
  data:
